// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqtktraoxpscithsmmww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxdGt0cmFveHBzY2l0aHNtbXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTQyNjAsImV4cCI6MjA3MDczMDI2MH0.6Z83s3qQy9GqCN3CTBrSGpKFwqm_Igklr-Fu3SGkiYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});